"""empty message

Revision ID: 603e1d8a2f1c
Revises: a53b6ae8fba4
Create Date: 2018-05-31 17:37:12.645000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '603e1d8a2f1c'
down_revision = 'a53b6ae8fba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('articles', sa.Column('type', sa.String(length=20), nullable=False))
    op.drop_column('articles', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('tag', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('articles', 'type')
    op.drop_column('articles', 'create_time')
    # ### end Alembic commands ###
