"""empty message

Revision ID: 930b4bca917b
Revises: 2db0dd5b7c7d
Create Date: 2018-06-13 13:35:01.451135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930b4bca917b'
down_revision = '2db0dd5b7c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_time')
    # ### end Alembic commands ###
