
# Application related configuration.
#


default: &default
    name: come_on_first
    login_expire: 7200
    max_content_length: 16777216
    api_version: /v1

development:
    <<: *default
    track_modifications: true
    echo: false

test:
    <<: *default
    track_modifications: true
    echo: false

staging:
    <<: *default
    track_modifications: true
    echo: false

production:
    <<: *default
    track_modifications: true
    echo: false

