# Redis configuration.
#


development:
    password:
    host: "127.0.0.1"
    port: 6379
    database: 1

test:
    password: $COF_REDIS_PASSWORD
    host: $COF_REDIS_HOST
    port: $COF_REDIS_PORT
    database: $COF_REDIS_DATABASE

staging:
    password: $COF_REDIS_PASSWORD
    host: $COF_REDIS_HOST
    port: $COF_REDIS_PORT
    database: $COF_REDIS_DATABASE

production:
    password: $COF_REDIS_PASSWORD
    host: $COF_REDIS_HOST
    port: $COF_REDIS_PORT
    database: $COF_REDIS_DATABASE