default: &default
    pool: 50

test:
    <<: *default
    user: root
    password: Admin.2@cd
    host: localhost
    port: 3306
    database: come_on_first

development:
    <<: *default
    user: $COME_MYSQL_USER
    password: $COME_MYSQL_PASSWORD
    host: $COME_MYSQL_HOST
    port: $COME_MYSQL_PORT
    database: $COME_MYSQL_DATABASE