
#development:
#    <<: *default
#    user: root
#    password: 123456
#    host: localhost
#    port: 3306
#    database: my_test
default: &default
    pool: 50

development:
    <<: *default
    user: $BOR_MYSQL_USER
    password: $BOR_MYSQL_PASSWORD
    host: $BOR_MYSQL_HOST
    port: $BOR_MYSQL_PORT
    database: $BOR_MYSQL_DATABASE