"""empty message

Revision ID: e20af5399257
Revises: 10c6615855e7
Create Date: 2018-05-29 17:05:38.860000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20af5399257'
down_revision = '10c6615855e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('tag', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'tag')
    # ### end Alembic commands ###
