"""add table autoalembic

Revision ID: 1d90f5992e84
Revises: 8a63803eb402
Create Date: 2018-06-19 15:22:27.832867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d90f5992e84'
down_revision = '8a63803eb402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('article_tag')
    op.drop_table('comments')
    op.drop_table('articles')
    op.drop_table('test')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tag_name', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('articles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], [u'users.id'], name=u'articles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], [u'articles.id'], name=u'comments_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'comments_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('article_tag',
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], [u'articles.id'], name=u'article_tag_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], [u'tags.id'], name=u'article_tag_ibfk_2'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
